apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronicle
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cronicle
  template:
    metadata:
      labels:
        app: cronicle
    spec:
      containers:
        - name: cronicle
          image: cronicle-universal:1.0.0
          command: ["/opt/cronicle/Cronicle-0.9.80/bin/control.sh", "start"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3012
          volumeMounts:
            - name: config
              mountPath: /opt/cronicle/data/conf.json
              subPath: conf.json
            - name: data
              mountPath: /opt/cronicle/data
      volumes:
        - name: config
          configMap:
            name: cronicle-config
        - name: data
          emptyDir: {}
---            

apiVersion: v1
kind: Service
metadata:
  name: cronicle
  namespace: default
spec:
  selector:
    app: cronicle
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3012
  type: NodePort
