apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronicle
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cronicle
  template:
    metadata:
      labels:
        app: cronicle
    spec:
      containers:
        - name: cronicle
          image: cronicle-universal:1.0.1
          imagePullPolicy: Never
          env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          ports:
            - containerPort: 3012
          volumeMounts:
            - name: config
              mountPath: /opt/cronicle/data/conf.json
              subPath: conf.json
            - name: data
              mountPath: /opt/cronicle/data
          command: ["/bin/sh", "-c"]
          args:
          - |
            sed -e "s/__HOSTNAME__/$HOSTNAME/g" /opt/cronicle/data/conf.template.json > /opt/cronicle/data/conf.json && \
            exec /opt/cronicle/Cronicle-0.9.80/bin/control.sh start && tail -f /dev/null   
      volumes:
        - name: config
          configMap:
            name: cronicle-config
        - name: data
          emptyDir: {}
---            

apiVersion: v1
kind: Service
metadata:
  name: cronicle
  namespace: default
spec:
  selector:
    app: cronicle
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3012
  type: NodePort
